export { api, apiFetch, apiUpload, setTokenSource, setRefreshHandler } from "./client";
export type { RequestOptions } from "./client";
export {
  getAccessToken,
  setSession,
  clearSession,
  hasSessionHint,
  refreshSession,
} from "./session";
export type { TokenPair } from "./session";
export { authApi, accountApi } from "./auth";
export type {
  AuthIdentity,
  AuthUser,
  AuthTokens,
  BackendPersona,
  LoginResult,
  RegisterResult,
  AccountPreferences,
  NotificationCategoryPref,
  AccountSession,
  SecurityEvent,
  TotpSetup,
} from "./auth";
export { organizationApi } from "./organization";
export type {
  Organization,
  OrgRole,
  OrgDepartment,
  OrgMember,
  OrgInvitation,
  PermissionInput,
  OrganizationPatch,
  PermissionPreview,
  MyCapabilities,
  OwnershipInfo,
  AuditLogEntry,
  ProfileQualityCheck,
  ProfileQuality,
  RecruiterSeats,
  CampusOwner,
  RiskFlagSeverity,
  OrgRiskFlag,
  OrgNote,
  CrmActivityRollup,
  HiringOutcomes,
} from "./organization";
export { jobsApi } from "./jobs";
export {
  EMPLOYMENT_TYPES,
  LOCATION_TYPES,
  JOB_VISIBILITIES,
  MODERATION_REASON_CODES,
} from "./jobs";
export type {
  JobStatus,
  ModerationStatus,
  ModerationReasonCode,
  BulkModerationResultItem,
  EmploymentType,
  LocationType,
  JobVisibility,
  JobSalary,
  JobCompanyRef,
  JobStudentFitSummary,
  JobStudentFitCvScore,
  JobStudentFitTier,
  JobStudentFitSignal,
  JobSummary,
  PublicJobDetail,
  OwnerJobSummary,
  OwnerJobDetail,
  JobCreateBody,
  JobUpdateBody,
  JdDraftInputs,
  JdDraftResult,
  JdUploadResult,
  CompetitionLevel,
  CompetitionSignal,
  JobTranslation,
  JobsConfig,
  StudentFitLabel,
  StudentFitBands,
  StudentJobFit,
  StudentCompetitionIntelligence,
  StudentLearningGap,
  StudentApplyReadiness,
  StudentNextActionType,
  StudentNextAction,
  StudentJobIntelligence,
  StudentFitExplanation,
  JobQualityIssueSeverity,
  JobQualityIssue,
  JobQualityCheckResult,
  JobPreviewPersona,
  JobPreviewResult,
  JobFitScoreEntry,
  BatchFitScoresResponse,
} from "./jobs";
export {
  eventsApi,
  EVENT_TYPES,
  EVENT_FORMATS,
  EVENT_STATUSES,
  EVENT_VISIBILITIES,
} from "./events";
export type {
  EventType,
  EventFormat,
  EventStatus,
  EventVisibility,
  EventModerationStatus,
  RegistrationState,
  EventVenue,
  EventCompanyRef,
  EventSummary,
  PublicEventDetail,
  OwnerEventSummary,
  OwnerEventDetail,
  EventAttendee,
  CheckInResult,
  EventCreateBody,
  EventUpdateBody,
  MyEventRegistration,
  CancelRegistrationResult,
} from "./events";
export { companiesApi } from "./companies";
export { reviewsApi } from "./reviews";
export type {
  CompanyReview,
  OwnReview,
  ModerationReview,
  CompanyRating,
  ReviewRatings,
  ReviewWriteBody,
  ModerationQueue,
} from "./reviews";
export type { CompanySummary, CompanyDetail } from "./companies";
export { marketplaceApi } from "./marketplace";
export type {
  MarketplaceMetrics,
  MarketplaceOverview,
  JobsTrend,
  JobsTrendPoint,
} from "./marketplace";
export { discoveryApi } from "./discovery";
export type {
  RecoSource,
  ReasonCode,
  SponsoredDisclosure,
  DisclosureClass,
  InventoryDisclosure,
  CampaignCreative,
  MarketplaceBanner,
  RecommendedJob,
  JobRecommendations,
  SimilarJobs,
  RecommendedEvent,
  SponsoredBanner,
  PopularRole,
  TrustModule,
  DiscoveryEventType,
  DiscoveryTargetType,
  DiscoverySourceSurface,
  CoarseSignalTags,
  DiscoveryEventInput,
  SessionResetResult,
} from "./discovery";
export { dashboardsApi } from "./dashboards";
export type {
  DashboardNextAction,
  CompletionSection,
  StudentDashboard,
  StudentDashboardMetrics,
  StudentRecentApplication,
  StudentUpcomingEvent,
  PartnerDashboard,
  PartnerDashboardMetrics,
  PartnerJobAttentionItem,
  PartnerRecentApplication,
  UniversityDashboard,
  UniversityDashboardMetrics,
  UniversityModerationItem,
  UniversityPartnerRequestItem,
  PartnerAnalytics,
  AnalyticsFunnelItem,
  AnalyticsTopJob,
  AnalyticsMonthlyPoint,
  PipelineJobRow,
  PartnerPipelineOverview,
  UniversityPlatformKpis,
  UniversityMonthlyPoint,
  UniversityPlatformStats,
  MarketEmploymentType,
  MarketSkill,
  UniversityMarketIntelligence,
  PartnerOpsTodo,
  PartnerEngagementTotals,
  PartnerEngagementWidget,
  PartnerOpsMetrics,
  PartnerJobPerformanceSourceMix,
  PartnerJobPerformanceRow,
  PartnerTopJobRow,
  PartnerJobPerformanceWidget,
  PartnerActivityItem,
  PartnerAccessAlertItem,
  PartnerAccessAlertsWidget,
  PartnerRbacSummary,
  PartnerAiRecommendation,
  PartnerDashboardOps,
  RecruitingFunnelStage,
  RecruitingStageOutcome,
  TimeBucket,
  TimeToHire,
  TimeInStageItem,
  PartnerRecruitingFunnel,
  AdvertisingCampaignRow,
  AdvertisingPerformanceTotals,
  PartnerAdvertisingPerformance,
} from "./dashboards";
export { analyticsApi } from "./analytics";
export type {
  JobEngagementEventType,
  JobEngagementSource,
  JobEngagementBody,
  JobEngagementResult,
  CandidateAccessEventType,
  CandidateAccessLogItem,
  CandidateAccessLog,
} from "./analytics";
export { careerOutcomesApi } from "./career-outcomes";
export type {
  CareerOutcomeKpi,
  CareerOutcomeTrustBucket,
  CareerOutcomeEmployer,
  CareerOutcomeRecord,
  CareerOutcomeRecords,
} from "./career-outcomes";
export {
  cvApi,
  isCvSourceRequiredError,
  newIdempotencyKey,
  parseCvQuotaError,
  patchElementStyle,
  resolveDownloadUrl,
  SELECTABLE_CREATION_MODES,
  TERMINAL_PARSE_STATUSES,
} from "./cv";
export type {
  CvCreationMode,
  CvQualityCode,
  CvNextAction,
  CvQuotaAction,
  CvLibraryMeta,
  CvListResult,
  CvQuotaInfo,
  ParseRunStatus,
  ExportStatus,
  CvTemplate,
  CvTemplateLayoutSchema,
  AdminCvTemplateCreateBody,
  AdminCvTemplateUpdateBody,
  CvSection,
  CvSectionContent,
  CvSectionItem,
  CvSummary,
  CvDetail,
  CvVersionSummary,
  CvReviewField,
  CvParseRun,
  CvUploadResult,
  CvExport,
  CvSourceInput,
  CreateCvBody,
  UpdateCvBody,
  SectionUpsertBody,
  SectionUpsertResult,
  DuplicateCvBody,
  ExportCvBody,
  JobFit,
  JobFitResult,
  JobFitBands,
  JobFitJobRef,
  JobFitSignal,
  CvCanvas,
  CvCanvasBlock,
  CvCanvasBlockStyle,
  CvCanvasPhoto,
  CvCanvasTheme,
  CvLinkType,
  ElementStyle,
  ElementStyleMap,
  ElementStyleSize,
  ElementStyleWeight,
  ElementStyleAlign,
  UpdateCvCanvasBody,
  UpdateCvPhotoBody,
  CvAiTaskType,
  CvAiSuggestionStatus,
  CvAiDiff,
  CvAiSectionSpec,
  CvAiSuggestion,
  AiSuggestionSourceIds,
  RequestAiSuggestionBody,
  AcceptAiSuggestionBody,
  AiEditCommandBody,
} from "./cv";
export {
  cvIngestionApi,
  rememberImportOrigin,
  readImportOrigin,
  parseFactConfirmationRequiredError,
  TERMINAL_INGESTION_STATUSES,
  INGESTION_PROGRESS_STEPS,
} from "./cv-ingestion";
export type {
  IngestionStatus,
  IngestionNextAction,
  IngestionQualityCode,
  UploadPreview,
  IngestionReviewField,
  Ingestion,
  ImportIngestionBody,
  ImportOrigin,
} from "./cv-ingestion";
export {
  applicationsApi,
  REJECTION_REASONS,
  SCORECARD_CRITERIA,
  SCORECARD_RECOMMENDATIONS,
  INTERVIEW_MODES,
  OFFER_LIVE_STATUSES,
  SALARY_PERIODS,
  SALARY_CURRENCIES,
} from "./applications";
export type {
  ApplicationStatus,
  ApplicationNextAction,
  ApplicationTimelineEvent,
  ApplicationMessagesPointer,
  RejectionReason,
  RejectBody,
  CvSelectionType,
  CvSelectionInput,
  ScreeningAnswers,
  ApplyBody,
  WithdrawBody,
  StudentApplication,
  PartnerApplicant,
  PartnerApplication,
  PartnerApplicationCv,
  CardAssignee,
  CandidateFit,
  CvDownloadInfo,
  StageRequiredAction,
  PipelineEvaluation,
  PipelineStage,
  PipelineCard,
  PipelineColumn,
  PipelineSummary,
  PipelineBoard,
  RollbackBody,
  ScorecardCriterionKey,
  ScorecardRecommendation,
  ScorecardScoreInput,
  SubmitScorecardBody,
  ScorecardScore,
  Scorecard,
  ScorecardAggregate,
  ScorecardCriterionMeta,
  ScorecardListResult,
  ScorecardAiSuggestBody,
  ScorecardAiCriterionSuggestion,
  ScorecardAiSuggestion,
  ScreeningBrief,
  InterviewMode,
  InterviewStatus,
  InterviewOutcome,
  InterviewAssignee,
  InterviewEvaluation,
  Interview,
  InterviewListResult,
  ScheduleInterviewBody,
  RescheduleInterviewBody,
  StudentInterviewCard,
  OfferStatus,
  OfferApproveDecision,
  OfferRespondDecision,
  SalaryPeriod,
  OfferCompFields,
  PartnerOffer,
  OfferListResult,
  OfferBoardGlance,
  StudentOffer,
  StudentOfferCard,
  CreateOfferBody,
  UpdateOfferBody,
  RespondOfferBody,
} from "./applications";
export { interviewPrepApi, coverLetterApi } from "./interview-prep";
export { mockInterviewApi, sessionListTitle, topJobTitle } from "./mock-interview";
export type {
  MockInterviewModality,
  MockInterviewSpeaker,
  MockInterviewStatus,
  MockInterviewFitSignal,
  MockInterviewJobRef,
  MockInterviewPrepCv,
  MockInterviewPrep,
  MockInterviewOpening,
  MockInterviewCaps,
  MockInterviewRealtimeDescriptor,
  MockInterviewSession,
  MockInterviewTranscriptTurn,
  CoachingReportQuestion,
  CoachingReport,
  MockInterviewSessionDetail,
  MockInterviewSessionListItem,
  MockInterviewProgressTheme,
  MockInterviewProgress,
  MockInterviewTrendPoint,
  MockInterviewTopJob,
  MockInterviewAdminStats,
  MockInterviewAdminConfig,
  MockInterviewFlaggedItem,
  MockInterviewAdminTranscriptMode,
  MockInterviewAdminTranscript,
  CreateMockInterviewBody,
  RecordTurnInput,
  RecordTurnsResult,
  EndSessionBody,
  TurnTokenEvent,
  TurnDoneEvent,
  TurnErrorEvent,
  TurnStreamEvent,
  StreamTurnHandlers,
} from "./mock-interview";
export { jobAlertsApi } from "./job-alerts";
export type { JobAlert, CreateJobAlertBody } from "./job-alerts";
export { aiAssistantApi } from "./ai-assistant";
export type {
  ChatSession,
  ChatMessage,
  ChatMessageRole,
  AiUsageSummary,
  AiUsageWindow,
  AiUsageDetail,
  AiUsageFeatureCount,
  AiUsageActivity,
} from "./ai-assistant";
export type {
  InterviewQuestion,
  InterviewPrepResult,
  InterviewPrepRequest,
  AnswerFeedbackRequest,
  AnswerFeedbackResult,
  CoverLetterResult,
  CoverLetterRequest,
} from "./interview-prep";
export {
  profileApi,
  PROFILE_VISIBILITIES,
  CONTACT_VISIBILITIES,
  OPEN_TO_WORK_TYPES,
  DEGREE_LEVELS,
} from "./profile";
export type {
  ProfileVisibility,
  ContactVisibility,
  OpenToWorkType,
  DegreeLevel,
  StudentProfile,
  PublicStudentProfile,
  UpdateProfileBody,
} from "./profile";
export { notificationsApi } from "./notifications";
export type {
  NotifType,
  Notification,
  NotificationPage,
  NotificationListResponse,
  MarkReadResult,
  MarkAllReadResult,
} from "./notifications";
export {
  templateAdminApi,
  NOTIFICATION_TEMPLATE_CHANNELS,
  NOTIFICATION_TEMPLATE_LOCALES,
  NOTIFICATION_TEMPLATE_STATUSES,
} from "./notifications";
export type {
  NotificationTemplateChannel,
  NotificationTemplateLocale,
  NotificationTemplateStatus,
  NotificationTemplateVariablesSchema,
  NotificationTemplate,
  NotificationTemplateCreateBody,
  NotificationTemplateUpdateBody,
  NotificationTemplatePreviewResult,
} from "./notifications";
export { messagingApi, newDedupeKey } from "./messaging";
export type {
  ThreadKind,
  ThreadContextType,
  ThreadStatus,
  ThreadSummary,
  ThreadParticipant,
  ThreadDetail,
  Message as MessagingMessage,
  MarkReadResult as MessagingMarkReadResult,
  MuteResult as MessagingMuteResult,
  DeleteMessageResult as MessagingDeleteMessageResult,
  ReportThreadResult as MessagingReportThreadResult,
  CreateThreadBody as MessagingCreateThreadBody,
  SendMessageBody as MessagingSendMessageBody,
} from "./messaging";
export {
  advertisingApi,
  PLACEMENT_STATUSES,
  CREATIVE_SLOTS,
  PRIMARY_CREATIVE_SLOTS,
  CREATIVE_SLOT_SPECS,
  ratioToCss,
  // Campaign allocation engine (spec §7.0)
  CAMPAIGN_STATUSES,
  CAMPAIGN_OBJECTIVES,
  CAMPAIGN_PACINGS,
  AD_SURFACES,
  COARSE_LOCATIONS,
  COARSE_MAJORS,
  COARSE_CAREERS,
  COARSE_WORK_MODES,
  COARSE_YEAR_COHORTS,
} from "./advertising";
export type {
  PlacementStatus,
  PlacementType,
  AdTargetType,
  AdPackage,
  Placement,
  AdvertisingSpend,
  CreatePlacementBody,
  UpdatePlacementBody,
  CreativeSlot,
  CreativeModerationStatus,
  CreativeDecision,
  CreativeAssetRequirements,
  PlacementCreative,
  UploadCreativeBody,
  // Campaign allocation engine (spec §7.0)
  CampaignStatus,
  CampaignObjective,
  CampaignPacing,
  AdSurface,
  DeliveryEventType,
  AdCampaign,
  AdCampaignCreative,
  CampaignTargeting,
  CampaignDelivery,
  CampaignPerformance,
  CampaignSpendSummary,
  AdSurfaceSlot,
  AllocationItem,
  AllocationSlot,
  AllocationCuratedFallback,
  SurfaceAllocation,
  CampaignAllocationRecord,
  CampaignCreativeInput,
  CampaignCreateBody,
  CampaignUpdateBody,
} from "./advertising";
export { billingApi, SUBSCRIPTION_STATUSES } from "./billing";
export type {
  SubscriptionStatus,
  BillingAudience,
  BillingPeriod,
  PlanLimits,
  SubscriptionPlan,
  Subscription,
  PaymentInstructions,
  SubscriptionRequestResult,
  MySubscription,
  BillingRevenue,
  AdminPlanCreateBody,
  AdminPlanUpdateBody,
} from "./billing";
export {
  aiSettingsApi,
  aiProvidersApi,
  aiAliasesApi,
  AI_MODEL_FAMILIES,
  AI_ROLLOUT_STATES,
  AI_ALIAS_FIELD,
  AI_PROVIDER_TYPES,
} from "./ai-settings";
export type {
  AiModelFamily,
  AiRolloutState,
  AiRealCallsStatus,
  AiModelAliases,
  AiAllowedAliases,
  AiFeatureFlags,
  AiSettings,
  AiSettingsUpdateBody,
  AiProvider,
  AiProviderType,
  AiProviderCreateBody,
  AiProviderUpdateBody,
  AiModelAliasRow,
  AiAliasCreateBody,
  AiAliasUpdateBody,
} from "./ai-settings";
export { careerServicesApi } from "./career-services";
export type {
  CohortStatus,
  CareerServicesCohort,
  CohortMembership,
  CohortCreateBody,
  CohortUpdateBody,
  RiskReason,
  RiskSeverity,
  RiskStatus,
  AtRiskFlag,
  AtRiskFlagCreateBody,
  CvReviewStatus,
  CvReviewPriority,
  CvReviewItem,
  CvReviewCreateBody,
  AppointmentStatus,
  AppointmentMode,
  CareerServicesAppointment,
  AppointmentCreateBody,
  NoteCategory,
  NoteVisibility,
  EmployerRelationshipNote,
  EmployerNoteCreateBody,
  EmployerNoteUpdateBody,
  InterventionType,
  InterventionOutcome,
  InterventionRecord,
  InterventionCreateBody,
  ReportingBucket,
  CareerServicesReportingSummary,
} from "./career-services";
export {
  RISK_REASONS,
  RISK_SEVERITIES,
  CV_REVIEW_PRIORITIES,
  CV_REVIEW_STATUSES,
  APPOINTMENT_MODES,
  APPOINTMENT_STATUSES,
  NOTE_CATEGORIES,
  NOTE_VISIBILITIES,
  INTERVENTION_TYPES,
  INTERVENTION_OUTCOMES,
} from "./career-services";
export { partnerApi } from "./partner";
export type {
  PartnerRegistrationBody,
  PartnerRegistrationResult,
  PartnerRegistration,
  TrustLevel,
} from "./partner";
export { ApiError, normalizeCode } from "./errors";
export type {
  ApiEnvelope,
  ApiListEnvelope,
  ApiPage,
  ApiErrorBody,
  ApiErrorCode,
} from "./types";
export { searchApi } from "./search";
export type { PopularKeywordsResponse, IndustryLeaf, IndustryBranch, IndustryRoot } from "./search";
export { locationsApi } from "./locations";
export type { Province, Ward } from "./locations";
export type { JobLocationItem } from "./jobs";
export { talentPoolApi } from "./talent-pool";
export type {
  MatchTier,
  TalentSearchSource,
  TalentMatch,
  TalentSearchPage,
  TalentSearchResult,
  TalentSearchBody,
} from "./talent-pool";
export { companyProfileApi, COMPANY_DOC_KINDS } from "./company-profile";
export type {
  CompanyChangeStatus,
  CompanyDocKind,
  CompanyDocument,
  CompanyChangeField,
  CompanyChangeRequest,
  CompanyProfile,
  CompanyProfileUpdateBody,
  CompanyProfileUpdateResult,
  CompanyApprovalDecisionResult,
} from "./company-profile";
export { adminUsersApi } from "./admin-users";
export type { AdminUserRow, AdminUsersPage, AdminUsersParams } from "./admin-users";
export { invitationsApi } from "./invitations";
export type {
  InvitationStatus,
  JobInvitation,
  InviteRespondResult,
  SendInviteBody,
} from "./invitations";
export { feedbackApi } from "./feedback";
export type { FeedbackBody, FeedbackResult } from "./feedback";
export {
  workflowsApi,
  SIDE_EFFECTING_NODE_TYPES,
  ADVISORY_NODE_TYPES,
  CONSEQUENTIAL_NODE_TYPES,
  HUMAN_CONFIRM_NODE_TYPES,
} from "./workflows";
export type {
  WorkflowNodeType,
  WorkflowOwnerType,
  FlowNode,
  FlowEdge,
  FlowGraph,
  WorkflowStatus,
  WorkflowFlow,
  CreateWorkflowBody,
  UpdateWorkflowBody,
  DryRunStep,
  DryRunResult,
  FailedNodeTaskStatus,
  FailedNodeTask,
} from "./workflows";
export { aiRoutingApi } from "./ai-routing";
export type {
  RoutingGraphNode,
  RoutingGraphEdge,
  RoutingGraph,
  RoutingGraphStatus,
  AiRoutingGraphRecord,
  RoutingProviderEntry,
  RoutingCanvasView,
} from "./ai-routing";
export { onboardingApi } from "./onboarding";
export type {
  OnboardingStatus,
  OnboardingRole,
  OnboardingStep,
  SeekerType,
  AiDocStatus,
  EmployerRequestStatus,
  SeekerProfilePayload,
} from "./onboarding";
export {
  supportApi,
  privacyApi,
  privacyAdminApi,
  abuseApi,
  REPORT_REASON_CODES,
  TRIAGE_SOURCES,
} from "./platform-trust";
export type {
  SupportUserRow,
  SupportOrgRow,
  SupportLookupResult,
  OutboxHealth,
  SupportCase,
  RevealedContact,
  ConsentType,
  ConsentState,
  ConsentsResponse,
  RetentionPolicyItem,
  PrivacyRequestType,
  PrivacyRequestStatus,
  PrivacyRequest,
  PrivacyRequestSubmitResult,
  ReportEntityType,
  ReportReasonCode,
  ContentReport,
  ContentReportSubmitResult,
  TriageContentReportItem,
  TriageReviewItem,
  TriageItem,
} from "./platform-trust";
