from app.modules.automation.infrastructure.models import AutomationWorkflow, WorkflowExecutionLog
from app.modules.ai_operations.infrastructure.interview_models import (
    AIInterviewSession,
    AIInterviewTurn,
)
from app.modules.engagement.infrastructure.models import CompanyReview, Notification
from app.modules.opportunities.infrastructure.models import (
    Bookmark,
    Event,
    EventRegistration,
    Job,
    JobScheduledAction,
)
from app.modules.recruitment.infrastructure.models import (
    CV,
    ApplicationTrackingLog,
    Interview,
    JobApplication,
)
from app.modules.reporting.infrastructure.models import (
    AIUsageLog,
    AuditLog,
    GeneratedReport,
    JobStatistic,
    UserActivityLog,
)
from app.platform.database.models.ai_runs import AIRun, AIRunEvent
from app.platform.database.models.base import SoftDeleteMixin, TimestampMixin, now_utc, uuid_str
from app.platform.database.models.identity import (
    Department,
    OIDCLoginTicket,
    Organization,
    Permission,
    Role,
    RolePermission,
    User,
    UserOIDCAccount,
    UserOrgRole,
    UserSession,
)
from app.platform.database.models.outbox import DocumentRecord, OutboxEvent
from app.platform.database.models.platform import (
    FeatureFlag,
    LegalDocument,
    SystemConfig,
    SystemWebhook,
    Translation,
    UserConsent,
)
from app.platform.database.models.registrations import (
    Industry,
    OrganizationIndustry,
    PartnerRegistration,
    RegistrationApplication,
    RegistrationEvidence,
    RegistrationHistory,
    RegistrationIndustry,
    StudentRegistration,
    VerificationPolicy,
)
from app.platform.database.models.student import (
    AcademicRecord,
    File,
    SkillDictionary,
    StudentProfile,
    UniversityMajor,
)

__all__ = [
    "AIRun",
    "AIRunEvent",
    "AIInterviewSession",
    "AIInterviewTurn",
    "AIUsageLog",
    "DocumentRecord",
    "OutboxEvent",
    "AcademicRecord",
    "ApplicationTrackingLog",
    "AutomationWorkflow",
    "AuditLog",
    "Bookmark",
    "CV",
    "CompanyReview",
    "Department",
    "Event",
    "EventRegistration",
    "FeatureFlag",
    "File",
    "GeneratedReport",
    "Interview",
    "Industry",
    "Job",
    "JobApplication",
    "JobScheduledAction",
    "JobStatistic",
    "LegalDocument",
    "Notification",
    "Organization",
    "OrganizationIndustry",
    "OIDCLoginTicket",
    "Permission",
    "PartnerRegistration",
    "Role",
    "RolePermission",
    "RegistrationApplication",
    "RegistrationEvidence",
    "RegistrationHistory",
    "RegistrationIndustry",
    "SkillDictionary",
    "SoftDeleteMixin",
    "StudentProfile",
    "StudentRegistration",
    "SystemConfig",
    "SystemWebhook",
    "TimestampMixin",
    "Translation",
    "UniversityMajor",
    "User",
    "UserOIDCAccount",
    "UserActivityLog",
    "UserConsent",
    "UserOrgRole",
    "UserSession",
    "VerificationPolicy",
    "WorkflowExecutionLog",
    "now_utc",
    "uuid_str",
]
