export const APP_BRAND_NAME = "VinUni Career";

type LocaleCode = "vi" | "en";

const LOCALE_TITLES: Record<LocaleCode, Record<string, string>> = {
  vi: {
    "/": "Trang chủ",
    "/auth/activate": "Kích hoạt tài khoản",
    "/auth/forgot-password": "Quên mật khẩu",
    "/auth/login": "Đăng nhập",
    "/auth/partner-registration": "Đăng ký đối tác",
    "/auth/register": "Đăng ký",
    "/auth/reset-password": "Đặt lại mật khẩu",
    "/auth/verify-email": "Xác minh email",
    "/career-explore": "Khám phá nghề nghiệp",
    "/companies": "Doanh nghiệp",
    "/employers": "Nhà tuyển dụng",
    "/events": "Sự kiện",
    "/jobs": "Tin tuyển dụng",
    "/partner": "Tổng quan",
    "/partner/advertising": "Quảng cáo",
    "/partner/analytics": "Phân tích",
    "/partner/billing": "Gói dịch vụ",
    "/partner/candidates": "Ứng viên",
    "/partner/company-profile": "Hồ sơ doanh nghiệp",
    "/partner/dashboard": "Tổng quan",
    "/partner/events": "Sự kiện",
    "/partner/events/new": "Tạo sự kiện",
    "/partner/jobs": "Tin tuyển dụng",
    "/partner/jobs/new": "Tạo tin tuyển dụng",
    "/partner/messages": "Tin nhắn",
    "/partner/notifications": "Thông báo",
    "/partner/ops": "Vận hành tuyển dụng",
    "/partner/pipeline": "Tuyển dụng",
    "/partner/reviews": "Đánh giá",
    "/partner/security": "Bảo mật & truy cập",
    "/partner/settings": "Cài đặt",
    "/partner/talent-pool": "Kho ứng viên",
    "/partner/team": "Thành viên & phân quyền",
    "/student": "Tổng quan",
    "/student/alerts": "Thông báo việc làm",
    "/student/applications": "Đơn ứng tuyển",
    "/student/billing": "Gói dịch vụ",
    "/student/cv": "CV",
    "/student/cv/import": "Nhập CV",
    "/student/dashboard": "Tổng quan",
    "/student/events": "Sự kiện",
    "/student/invitations": "Lời mời ứng tuyển",
    "/student/messages": "Tin nhắn",
    "/student/notifications": "Thông báo",
    "/student/profile": "Hồ sơ",
    "/student/saved": "Việc làm đã lưu",
    "/student/settings": "Cài đặt",
    "/university": "Tổng quan",
    "/university/advertising": "Quảng cáo",
    "/university/ai-settings": "Cài đặt AI",
    "/university/ai-settings/routing": "Điều phối AI",
    "/university/billing": "Gói dịch vụ",
    "/university/career-outcomes": "Kết quả nghề nghiệp",
    "/university/career-services": "Dịch vụ hướng nghiệp",
    "/university/career-services/cohorts": "Nhóm sinh viên",
    "/university/career-services/at-risk": "Sinh viên có rủi ro",
    "/university/career-services/cv-review": "Hàng đợi duyệt CV",
    "/university/career-services/appointments": "Lịch hẹn tư vấn",
    "/university/career-services/employer-notes": "Ghi chú nhà tuyển dụng",
    "/university/career-services/interventions": "Lịch sử can thiệp",
    "/university/cv-templates": "Mẫu CV",
    "/university/ai-governance": "Quản trị AI",
    "/university/dashboard": "Tổng quan",
    "/university/events": "Sự kiện",
    "/university/messages": "Tin nhắn",
    "/university/moderation": "Kiểm duyệt",
    "/university/moderation/events": "Duyệt sự kiện",
    "/university/moderation/jobs": "Duyệt tin tuyển dụng",
    "/university/notifications": "Thông báo",
    "/university/partners": "Đối tác",
    "/university/reports": "Báo cáo",
    "/university/reviews": "Đánh giá",
    "/university/settings": "Cài đặt",
    "/university/users": "Người dùng",
    "/university/support": "Bảng hỗ trợ",
    "/university/privacy": "Yêu cầu quyền riêng tư",
    "/university/abuse": "Xử lý báo cáo vi phạm",
    "/university/workflow": "Quy trình",
    "/university/workflow/new": "Tạo quy trình",
    "/university/platform-overview": "Tổng quan nền tảng",
    "/university/ai-operations": "Vận hành AI",
    "/university/audit-log": "Nhật ký kiểm tra",
    "/university/system-health": "Tình trạng hệ thống",
    "/admin": "Quản trị nền tảng",
    "/admin/platform-overview": "Tổng quan nền tảng",
    "/admin/analytics": "Phân tích",
    "/admin/ai-operations": "Vận hành AI",
    "/admin/ai-distribution": "Phân bổ năng lượng AI",
    "/admin/system-health": "Tình trạng hệ thống",
    "/admin/alerts": "Cảnh báo",
    "/admin/logs": "Nhật ký",
    "/admin/audit-log": "Nhật ký kiểm tra",
    "/admin/feature-flags": "Cờ tính năng",
    "/admin/access": "Người dùng & phân quyền",
  },
  en: {
    "/": "Home",
    "/auth/activate": "Activate account",
    "/auth/forgot-password": "Forgot password",
    "/auth/login": "Sign in",
    "/auth/partner-registration": "Partner registration",
    "/auth/register": "Create account",
    "/auth/reset-password": "Reset password",
    "/auth/verify-email": "Verify email",
    "/career-explore": "Career explore",
    "/companies": "Companies",
    "/employers": "Employers",
    "/events": "Events",
    "/jobs": "Job posts",
    "/partner": "Overview",
    "/partner/advertising": "Advertising",
    "/partner/analytics": "Analytics",
    "/partner/billing": "Plans",
    "/partner/candidates": "Candidates",
    "/partner/company-profile": "Company profile",
    "/partner/dashboard": "Overview",
    "/partner/events": "Events",
    "/partner/events/new": "Create event",
    "/partner/jobs": "Job posts",
    "/partner/jobs/new": "Create job post",
    "/partner/messages": "Messages",
    "/partner/notifications": "Notifications",
    "/partner/ops": "Recruiting operations",
    "/partner/pipeline": "Recruiting",
    "/partner/reviews": "Reviews",
    "/partner/security": "Access & security",
    "/partner/settings": "Settings",
    "/partner/talent-pool": "Talent pool",
    "/partner/team": "Team & permissions",
    "/student": "Overview",
    "/student/alerts": "Job alerts",
    "/student/applications": "Applications",
    "/student/billing": "Plans",
    "/student/cv": "CV",
    "/student/cv/import": "Import CV",
    "/student/dashboard": "Overview",
    "/student/events": "Events",
    "/student/invitations": "Invitations",
    "/student/messages": "Messages",
    "/student/notifications": "Notifications",
    "/student/profile": "Profile",
    "/student/saved": "Saved jobs",
    "/student/settings": "Settings",
    "/university": "Overview",
    "/university/advertising": "Advertising",
    "/university/ai-settings": "AI settings",
    "/university/ai-settings/routing": "AI routing",
    "/university/billing": "Plans",
    "/university/career-outcomes": "Career outcomes",
    "/university/career-services": "Career services",
    "/university/career-services/cohorts": "Cohorts",
    "/university/career-services/at-risk": "At-risk students",
    "/university/career-services/cv-review": "CV review queue",
    "/university/career-services/appointments": "Appointments",
    "/university/career-services/employer-notes": "Employer notes",
    "/university/career-services/interventions": "Intervention history",
    "/university/cv-templates": "CV templates",
    "/university/ai-governance": "AI Governance",
    "/university/dashboard": "Overview",
    "/university/events": "Events",
    "/university/messages": "Messages",
    "/university/moderation": "Moderation",
    "/university/moderation/events": "Event moderation",
    "/university/moderation/jobs": "Job moderation",
    "/university/notifications": "Notifications",
    "/university/partners": "Partners",
    "/university/reports": "Reports",
    "/university/reviews": "Reviews",
    "/university/settings": "Settings",
    "/university/users": "Users",
    "/university/support": "Support console",
    "/university/privacy": "Privacy requests",
    "/university/abuse": "Abuse triage",
    "/university/workflow": "Workflow",
    "/university/workflow/new": "Create workflow",
    "/university/platform-overview": "Platform Overview",
    "/university/ai-operations": "AI Operations",
    "/university/audit-log": "Audit Log",
    "/university/system-health": "System Health",
    "/admin": "Platform Admin",
    "/admin/platform-overview": "Platform Overview",
    "/admin/analytics": "Analytics",
    "/admin/ai-operations": "AI Operations",
    "/admin/ai-distribution": "AI Energy Distribution",
    "/admin/system-health": "System Health",
    "/admin/alerts": "Alerts",
    "/admin/logs": "Logs",
    "/admin/audit-log": "Audit Log",
    "/admin/feature-flags": "Feature Flags",
    "/admin/access": "Users & Access",
  },
};

const DYNAMIC_TITLES: Record<LocaleCode, Array<[RegExp, string]>> = {
  vi: [
    [/^\/companies\/[^/]+$/, "Hồ sơ doanh nghiệp"],
    [/^\/events\/[^/]+$/, "Chi tiết sự kiện"],
    [/^\/jobs\/[^/]+\/interview-sim$/, "Phỏng vấn thử"],
    [/^\/jobs\/[^/]+$/, "Chi tiết tin tuyển dụng"],
    [/^\/partner\/events\/[^/]+$/, "Chi tiết sự kiện"],
    [/^\/partner\/jobs\/[^/]+\/applications$/, "Ứng viên"],
    [/^\/partner\/jobs\/[^/]+\/pipeline$/, "Pipeline ứng viên"],
    [/^\/partner\/jobs\/[^/]+$/, "Chi tiết tin tuyển dụng"],
    [/^\/partner\/talent\/[^/]+$/, "Hồ sơ ứng viên"],
    [/^\/student\/applications\/[^/]+$/, "Chi tiết đơn ứng tuyển"],
    [/^\/student\/cv\/[^/]+$/, "CV"],
    [/^\/university\/workflow\/[^/]+$/, "Chi tiết quy trình"],
  ],
  en: [
    [/^\/companies\/[^/]+$/, "Company profile"],
    [/^\/events\/[^/]+$/, "Event details"],
    [/^\/jobs\/[^/]+\/interview-sim$/, "Interview simulator"],
    [/^\/jobs\/[^/]+$/, "Job post details"],
    [/^\/partner\/events\/[^/]+$/, "Event details"],
    [/^\/partner\/jobs\/[^/]+\/applications$/, "Candidates"],
    [/^\/partner\/jobs\/[^/]+\/pipeline$/, "Candidate pipeline"],
    [/^\/partner\/jobs\/[^/]+$/, "Job post details"],
    [/^\/partner\/talent\/[^/]+$/, "Candidate profile"],
    [/^\/student\/applications\/[^/]+$/, "Application details"],
    [/^\/student\/cv\/[^/]+$/, "CV"],
    [/^\/university\/workflow\/[^/]+$/, "Workflow details"],
  ],
};

export function normalizeLocale(locale: string): LocaleCode {
  return locale === "en" ? "en" : "vi";
}

export function getRouteTitle(pathname: string, locale: string): string | null {
  const normalizedLocale = normalizeLocale(locale);
  const normalizedPathname = normalizePathname(pathname);
  const exactTitle = LOCALE_TITLES[normalizedLocale][normalizedPathname];
  if (exactTitle) return exactTitle;

  const dynamicTitle = DYNAMIC_TITLES[normalizedLocale].find(([pattern]) =>
    pattern.test(normalizedPathname),
  );
  return dynamicTitle?.[1] ?? null;
}

export function composeDocumentTitle(routeTitle: string | null): string {
  return routeTitle ? `${routeTitle} | ${APP_BRAND_NAME}` : APP_BRAND_NAME;
}

function normalizePathname(pathname: string): string {
  const withoutLocale = pathname.replace(/^\/(vi|en)(?=\/|$)/, "");
  const withoutTrailingSlash = withoutLocale.replace(/\/+$/, "");
  return withoutTrailingSlash || "/";
}
